export type Category = 'all' | 'housing' | 'findhousing' | 'jobs' | 'sell' | 'services'

export type SortOption = 'new' | 'old' | 'pa' | 'pd' | 'pop'

export interface User {
  id: string
  name: string
  phone?: string
  avatar_url?: string
  city: string
  rating: number
  ads_count: number
  created_at: string
  whatsapp?: string
  telegram?: string
  vk?: string
}

export interface Listing {
  id: string
  user_id: string
  title: string
  description: string
  category: Category
  price?: number
  metro?: string
  city: string
  phone?: string
  photos: string[]
  views: number
  status: 'active' | 'draft' | 'deleted'
  is_urgent: boolean
  is_premium: boolean
  created_at: string
  user?: User
  // legacy — не использовать в новом коде
  is_active?: boolean
  expires_at?: string
}

export interface Message {
  id: string
  listing_id: string
  sender_id: string
  receiver_id: string
  text: string
  is_read: boolean
  created_at: string
  sender?: User
}

export interface Review {
  id: string
  reviewer_id: string
  reviewed_id: string
  listing_id: string
  rating: number
  comment: string
  created_at: string
  reviewer?: User
}

export interface Favorite {
  id: string
  user_id: string
  listing_id: string
  created_at: string
  listing?: Listing
}

export interface FilterState {
  category: Category
  query: string
  city: string
  metro: string
  priceMin: string
  priceMax: string
  sort: SortOption
}

export const DEFAULT_CITY = 'Москва'

export const COUNTRIES = [
  { id: 'Россия',      flag: '🇷🇺' },
  { id: 'Германия',    flag: '🇩🇪' },
  { id: 'Англия',      flag: '🇬🇧' },
  { id: 'Америка',     flag: '🇺🇸' },
  { id: 'Корея',       flag: '🇰🇷' },
  { id: 'Кыргызстан',  flag: '🇰🇬' },
]

export const CITIES = [
  // Россия
  { id: 'Москва',           flag: '🏙️', country: 'Россия',      metro: true  },
  { id: 'Санкт-Петербург',  flag: '🌉', country: 'Россия',      metro: true  },
  { id: 'Екатеринбург',     flag: '🏙️', country: 'Россия',      metro: true  },
  { id: 'Новосибирск',      flag: '🏙️', country: 'Россия',      metro: true  },
  { id: 'Казань',           flag: '🏙️', country: 'Россия',      metro: true  },
  { id: 'Краснодар',        flag: '🏙️', country: 'Россия',      metro: false },
  // Германия — все крупные города имеют U-Bahn
  { id: 'Берлин',           flag: '🏙️', country: 'Германия',    metro: true  },
  { id: 'Мюнхен',           flag: '🏙️', country: 'Германия',    metro: true  },
  { id: 'Гамбург',          flag: '🌉', country: 'Германия',    metro: true  },
  { id: 'Франкфурт',        flag: '🏙️', country: 'Германия',    metro: true  },
  { id: 'Кёльн',            flag: '🏙️', country: 'Германия',    metro: true  },
  { id: 'Дюссельдорф',      flag: '🏙️', country: 'Германия',    metro: true  },
  // Англия
  { id: 'Лондон',           flag: '🏙️', country: 'Англия',      metro: true  },
  { id: 'Манчестер',        flag: '🏙️', country: 'Англия',      metro: true  },
  { id: 'Ливерпуль',        flag: '🏙️', country: 'Англия',      metro: true  },
  { id: 'Глазго',           flag: '🏙️', country: 'Англия',      metro: true  },
  { id: 'Бирмингем',        flag: '🏙️', country: 'Англия',      metro: false },
  { id: 'Лидс',             flag: '🏙️', country: 'Англия',      metro: false },
  // Америка
  { id: 'Нью-Йорк',         flag: '🗽', country: 'Америка',     metro: true  },
  { id: 'Лос-Анджелес',     flag: '🌴', country: 'Америка',     metro: true  },
  { id: 'Чикаго',           flag: '🏙️', country: 'Америка',     metro: true  },
  { id: 'Вашингтон',        flag: '🏛️', country: 'Америка',     metro: true  },
  { id: 'Сан-Франциско',    flag: '🌉', country: 'Америка',     metro: true  },
  { id: 'Майами',           flag: '🌊', country: 'Америка',     metro: true  },
  // Корея — все крупные города имеют метро
  { id: 'Сеул',             flag: '🏙️', country: 'Корея',       metro: true  },
  { id: 'Пусан',            flag: '🌊', country: 'Корея',       metro: true  },
  { id: 'Инчхон',           flag: '🏙️', country: 'Корея',       metro: true  },
  { id: 'Тэгу',             flag: '🏙️', country: 'Корея',       metro: true  },
  { id: 'Тэджон',           flag: '🏙️', country: 'Корея',       metro: true  },
  { id: 'Кванджу',          flag: '🏙️', country: 'Корея',       metro: true  },
  // Кыргызстан — метро нет
  { id: 'Бишкек',           flag: '🏔️', country: 'Кыргызстан',  metro: false },
  { id: 'Ош',               flag: '🏙️', country: 'Кыргызстан',  metro: false },
  { id: 'Джалал-Абад',      flag: '🏙️', country: 'Кыргызстан',  metro: false },
  { id: 'Кант',             flag: '🏙️', country: 'Кыргызстан',  metro: false },
  { id: 'Нарын',            flag: '🏔️', country: 'Кыргызстан',  metro: false },
  { id: 'Токмок',           flag: '🏙️', country: 'Кыргызстан',  metro: false },
]

export const CATEGORIES: { id: Category; label: string; icon: string; color: string }[] = [
  { id: 'housing',     label: 'Батир берем',   icon: '🏠', color: 'blue'   },
  { id: 'findhousing', label: 'Батир издейм',  icon: '🔍', color: 'indigo' },
  { id: 'jobs',        label: 'Жумуш',         icon: '💼', color: 'green'  },
  { id: 'sell',        label: 'Сатам/Алам',    icon: '🛍️', color: 'amber'  },
  { id: 'services',    label: 'Кызматтар',     icon: '🔧', color: 'purple' },
]

export const METRO_STATIONS = [
  'Авиамоторная',
  'Автозаводская',
  'Академическая',
  'Александровский сад',
  'Алексеевская',
  'Алма-Атинская',
  'Алтуфьево',
  'Аннино',
  'Арбатская',
  'Аэропорт',
  'Бабушкинская',
  'Багратионовская',
  'Балтийская',
  'Баррикадная',
  'Бауманская',
  'Беговая',
  'Бибирево',
  'Библиотека им. Ленина',
  'Битцевский парк',
  'Борисово',
  'Боровицкая',
  'Боровское шоссе',
  'Ботанический сад',
  'Братиславская',
  'Бульвар Адмирала Ушакова',
  'Бульвар Дмитрия Донского',
  'Бульвар Рокоссовского',
  'Бунинская аллея',
  'Бутово',
  'ВДНХ',
  'Варшавская',
  'Верхние Котлы',
  'Верхние Лихоборы',
  'Владыкино',
  'Войковская',
  'Волгоградский проспект',
  'Волжская',
  'Волоколамская',
  'Воробьёвы горы',
  'Выхино',
  'Говорово',
  'Горьковская',
  'Деловой центр',
  'Дмитровская',
  'Добрынинская',
  'Домодедовская',
  'Достоевская',
  'Дубровка',
  'Зябликово',
  'Измайловская',
  'Калужская',
  'Кантемировская',
  'Каховская',
  'Каширская',
  'Киевская',
  'Китай-город',
  'Кожуховская',
  'Коломенская',
  'Комсомольская',
  'Коньково',
  'Коптево',
  'Косино',
  'Красногвардейская',
  'Красносельская',
  'Красные Ворота',
  'Краснопресненская',
  'Крестьянская застава',
  'Кропоткинская',
  'Крылатское',
  'Кузьминки',
  'Кунцевская',
  'Курская',
  'Кутузовская',
  'Ленинский проспект',
  'Лермонтовский проспект',
  'Лесопарковая',
  'Лихоборы',
  'Ломоносовский проспект',
  'Лубянка',
  'Люблино',
  'Марьина Роща',
  'Марьино',
  'Маяковская',
  'Медведково',
  'Менделеевская',
  'Мичуринский проспект',
  'Митино',
  'Молодёжная',
  'Мякинино',
  'Нагатинская',
  'Нагорная',
  'Нахимовский проспект',
  'Некрасовка',
  'Нижегородская',
  'Новогиреево',
  'Новокосино',
  'Новокузнецкая',
  'Новопеределкино',
  'Новослободская',
  'Новохохловская',
  'Новые Черёмушки',
  'Обухово',
  'Октябрьская',
  'Октябрьское поле',
  'Орехово',
  'Отрадное',
  'Охотный Ряд',
  'Павелецкая',
  'Парк Культуры',
  'Парк Победы',
  'Партизанская',
  'Первомайская',
  'Перово',
  'Петровско-Разумовская',
  'Печатники',
  'Пионерская',
  'Планерная',
  'Площадь Гагарина',
  'Площадь Ильича',
  'Площадь Революции',
  'Полежаевская',
  'Полянка',
  'Пражская',
  'Преображенская площадь',
  'Проспект Вернадского',
  'Проспект Мира',
  'Профсоюзная',
  'Пушкинская',
  'Раменки',
  'Рассказовка',
  'Рижская',
  'Румянцево',
  'Рязанский проспект',
  'Савёловская',
  'Саларьево',
  'Свиблово',
  'Семёновская',
  'Серпуховская',
  'Сетунь',
  'Славянский бульвар',
  'Смоленская',
  'Солнцево',
  'Сокол',
  'Соколиная Гора',
  'Сокольники',
  'Спартак',
  'Спортивная',
  'Строгино',
  'Студенческая',
  'Сухаревская',
  'Сходненская',
  'Таганская',
  'Тверская',
  'Театральная',
  'Текстильщики',
  'Теплый Стан',
  'Технопарк',
  'Тимирязевская',
  'Третьяковская',
  'Тропарёво',
  'Трубная',
  'Тульская',
  'Тургеневская',
  'Угрешская',
  'Улица 1905 года',
  'Улица Академика Янгеля',
  'Улица Горчакова',
  'Улица Скобелевская',
  'Улица Старокачаловская',
  'Университет',
  'Филёвский парк',
  'Фили',
  'Фонвизинская',
  'Фрунзенская',
  'Царицыно',
  'Цветной бульвар',
  'Черкизовская',
  'Чертановская',
  'Чистые пруды',
  'Чкаловская',
  'Шаболовская',
  'Шипиловская',
  'Шоссе Энтузиастов',
  'Щёлковская',
  'Щукинская',
  'Электрозаводская',
  'Юго-Западная',
  'Южная',
  'Ясенево',
].sort((a, b) => a.localeCompare(b, 'ru'))

export const METRO_BY_CITY: Record<string, string[]> = {
  'Москва': METRO_STATIONS,
  'Санкт-Петербург': [
    'Автово','Адмиралтейская','Академическая','Балтийская','Беговая',
    'Бухарестская','Василеостровская','Волковская','Выборгская','Горьковская',
    'Гостиный двор','Девяткино','Дунайская','Елизаровская','Звёздная',
    'Зенит','Кировский завод','Комендантский проспект','Купчино','Ладожская',
    'Лесная','Лиговский проспект','Ломоносовская','Международная','Московская',
    'Московские ворота','Нарвская','Невский проспект','Новочеркасская',
    'Обводный канал','Обухово','Озерки','Парк победы','Парнас',
    'Петроградская','Пионерская','Площадь Александра Невского','Площадь Восстания',
    'Площадь Мужества','Политехническая','Приморская','Пролетарская',
    'Проспект Большевиков','Проспект Ветеранов','Проспект Просвещения',
    'Рыбацкое','Садовая','Спортивная','Старая деревня',
    'Технологический институт','Удельная','Улица Дыбенко','Фрунзенская',
    'Чёрная речка','Чернышевская','Чкаловская','Шушары','Электросила',
  ].sort((a, b) => a.localeCompare(b, 'ru')),
  'Екатеринбург': [
    'Ботаническая','Геологическая','Динамо','Машиностроителей',
    'Площадь 1905 года','Проспект Космонавтов','Уралмаш','Уральская','Чкаловская',
  ],
  'Новосибирск': [
    'Берёзовая роща','Гагаринская','Золотая нива','Заельцовская',
    'Красный проспект','Маршала Покрышкина','Октябрьская',
    'Площадь Гарина-Михайловского','Площадь Ленина','Площадь Маркса',
    'Речной вокзал','Сибирская','Студенческая',
  ],
  'Казань': [
    'Авиастроительная','Аметьево','Горки','Дубравная','Козья слобода',
    'Кремлёвская','Молодёжная','Площадь Тукая','Проспект Победы',
    'Суконная слобода','Яшьлек',
  ],
  'Берлин': [
    'Adenauerplatz','Afrikanische Straße','Alexanderplatz','Alt-Mariendorf',
    'Alt-Tempelhof','Alt-Tegel','Altstadt Spandau','Amrumer Straße',
    'Anton-Wilhelm-Amo-Straße','Augsburger Straße','Bayerischer Platz',
    'Berliner Straße','Bernauer Straße','Birkenstraße','Bismarckstraße',
    'Blissestraße','Borsigwerke','Brandenburger Tor','Breitenbachplatz',
    'Bülowstraße','Bundestag','Bundesplatz','Dahlem-Dorf',
    'Deutsche Oper','Ernst-Reuter-Platz','Fehrbelliner Platz',
    'Franz-Neumann-Platz','Friedrich-Wilhelm-Platz','Friedrichstraße',
    'Gesundbrunnen','Gleisdreieck','Gneisenaustraße','Güntzelstraße',
    'Hallesches Tor','Hansaplatz','Haselhorst','Hauptbahnhof',
    'Hausvogteiplatz','Heinrich-Heine-Straße','Heidelberger Platz',
    'Hermannplatz','Hohenzollernplatz','Holzhauser Straße',
    'Innsbrucker Platz','Jakob-Kaiser-Platz','Jannowitzbrücke',
    'Kaiserdamm','Kaiserin-Augusta-Straße','Karl-Bonhoeffer-Nervenklinik',
    'Kleistpark','Klosterstraße','Kochstraße','Konstanzer Straße',
    'Kottbusser Tor','Krumme Lanke','Kurt-Schumacher-Platz',
    'Kurfürstendamm','Kurfürstenstraße','Leopoldplatz','Lindauer Allee',
    'Märkisches Museum','Mehringdamm','Mendelssohn-Bartholdy-Park',
    'Mierendorffplatz','Möckernbrücke','Moritzplatz','Museumsinsel',
    'Naturkundemuseum','Nauener Platz','Neu-Westend','Nollendorfplatz',
    'Nollendorfplatz','Olympia-Stadion','Onkel Toms Hütte',
    'Oranienburger Tor','Oskar-Helene-Heim','Otisstraße','Pankstraße',
    'Paracelsus-Bad','Paradestraße','Paulsternstraße','Platz der Luftbrücke',
    'Podbielskiallee','Potsdamer Platz','Prinzenstraße','Rathaus Reinickendorf',
    'Rathaus Schöneberg','Rathaus Spandau','Rathaus Steglitz','Rathaus Steglitz',
    'Rehberge','Residenzstraße','Richard-Wagner-Platz','Rohrdamm',
    'Rosenthaler Platz','Rotes Rathaus','Rüdesheimer Platz','Ruhleben',
    'Scharnweberstraße','Schloßstraße','Schwartzkopffstraße','Seestraße',
    'Siemensdamm','Sophie-Charlotte-Platz','Spichernstraße','Spittelmarkt',
    'Stadtmitte','Stadtmitte','Südstern','Tempelhof','Theodor-Heuss-Platz',
    'Thielplatz','Turmstraße','Uhlandstraße','Ullsteinstraße','Unter den Linden',
    'Viktoria-Luise-Platz','Voltastraße','Walther-Schreiber-Platz',
    'Wedding','Weinmeisterstraße','Westend','Westhafen','Westphalweg',
    'Wilmersdorfer Straße','Wittenbergplatz','Wittenau','Yorckstraße',
    'Zoologischer Garten','Zitadelle',
  ].sort(),
  'Мюнхен': [
    'Arabellapark','Brudermühlstraße','Candidplatz','Dülferstraße',
    'Forstenrieder Allee','Fröttmaning','Garching','Garching-Forschungszentrum',
    'Georg-Brauchle-Ring','Giesing','Giesing','Großhadern','Harras',
    'Hauptbahnhof','Heimeranplatz','Implerstraße','Innsbrucker Ring',
    'Isartor','Karl-Preis-Platz','Karlsplatz (Stachus)','Kieferngarten',
    'Kolumbusplatz','Kurfürstenplatz','Laimer Platz','Lehel',
    'Leienfelsstraße','Leonrodplatz','Maillingerstraße','Mangfallplatz',
    'Marienplatz','Max-Weber-Platz','Maximilianeum','Messestadt Ost',
    'Messestadt West','Moosach','Moosfeld','Münchner Freiheit',
    'Neuperlach Süd','Neuperlach Zentrum','Nordfriedhof',
    'Obersendling','Odeonsplatz','Olympia-Einkaufszentrum',
    'Olympiazentrum','Ostbahnhof','Partnachplatz','Poccistraße',
    'Prinzregentenplatz','Quiddestraße','Rotkreuzplatz','Scheidplatz',
    'Schwabing Nord','Schwanthalerhöhe','Sendlinger Tor','St.-Quirin-Platz',
    'Theresienwiese','Trudering','Universität','Westfriedhof',
  ].sort(),
  'Гамбург': [
    'Ahrensburg Ost','Ahrensburg West','Alsterdorf','Altona',
    'Barmbek','Berliner Tor','Billstedt','Berne','Borstelmannsweg',
    'Dehnhaide','Duvenacker','Elmshorn','Eppendorfer Baum',
    'Farmsen','Fuhlsbüttel','Fuhlsbüttel Nord','Garstedt','Großhansdorf',
    'Hagenbecks Tierpark','Hamburger Meile','Hammerbrook','Harburg Rathaus',
    'Harvestehude','Hauptbahnhof','Horner Rennbahn','Hoheluftbrücke',
    'Hudtwalckerstraße','Jungfernstieg','Kellinghusenstraße','Klein Borstel',
    'Klosterstern','Königstraße','Langenfelde','Langenhorn Markt',
    'Langenhorn Nord','Lattenkamp','Lübecker Straße','Lübecker Straße',
    'Meiendorfer Weg','Merkenstraße','Mümmelmannsberg','Niendorf Markt',
    'Niendorf Nord','Ohlsdorf','Oldenfelde','Othmarschen','Papenhuder Straße',
    'Rahlstedt','Rathaus','Rödingsmarkt','Rübenkamp','Sengelmannstraße',
    'Sierichstraße','Steinfurther Allee','Stephansplatz','Stückenstraße',
    'Trabrennbahn','Überseequartier','Uhlandstraße','Volksdorf',
    'Wandsbek Markt','Wandsbek-Gartenstadt','Wandsbeker Chaussee',
    'Weinberg','Wellingsbüttel',
  ].sort(),
  'Франкфурт': [
    'Alte Oper','Bad Homburg Bahnhof','Bad Vilbel','Bettenhausen',
    'Bockenheimer Warte','Bornheim Mitte','Dornbusch','Eckenheim',
    'Eschenheimer Tor','Festhalle/Messe','Frankenallee','Frankfurt Hauptbahnhof',
    'Friedberger Warte','Ginnheim','Grüneburgweg','Günnigfeld',
    'Hauptwache','Hausen','Höchst','Hügelstraße',
    'Industriehof','Isenburg Zentrum','Kalbach','Kirchheimer Straße',
    'Konstablerwache','Lerschstraße','Louisa','Merianplatz',
    'Messe','Miquel-/Adickesallee','Mühlberg','Naturkundemuseum',
    'Niddapark','Nieder-Eschbach','Niederrad','Nordwestzentrum',
    'Oberursel Bahnhof','Obertshausen','Offenbach Marktplatz',
    'Ostbahnhof','Ostend','Preungesheim','Rödelheim',
    'Römer/Paulskirche','Sachsenhausen Nord','Sachsenhausen Süd',
    'Schäfflestraße','Seckbach','Sindlingen','Sömmeringstraße',
    'Südbahnhof','Theaterplatz','Willy-Brandt-Platz','Zoo',
  ].sort(),
  'Кёльн': [
    'Appellhofplatz','Aachener Straße/Gürtel','Bickendorf',
    'Bonner Wall','Breslauer Platz/Hauptbahnhof','Chlodwigplatz',
    'Deutz/Messe','Dom/Hauptbahnhof','Ebertplatz','Ehrenfeldgürtel',
    'Eifelplatz','Geldernstraße/Parkgürtel','Heumarkt',
    'Kalk Post','Karlsplatz','Klettenbergpark','Kölnarena',
    'Lindenthal','Mülheimer Freiheit','Neumarkt','Nußbaumerstraße',
    'Poststraße','Rudolfplatz','Severinstraße','Schleußweg',
    'Subbelrather Straße/Gürtel','Wiener Platz','Weiden West',
    'Zollstock Süd','Zülpicher Platz',
  ].sort(),
  'Дюссельдорф': [
    'Am Steinberg','Auf dem Rüssel','Benrath','Bilk',
    'Düsseldorf Flughafen','Eller Mitte','Flingern','Flughafen Terminal',
    'Friedrich-Ebert-Straße','Graf-Adolf-Platz','Grafenberg',
    'Handelszentrum','Hauptbahnhof','Heinrich-Heine-Allee',
    'Holthausen','Hubbelrath','Jan-Wellem-Platz','Landtag/Arena',
    'Mörsenbroich','Nordstraße','Oberbilk','Oststraße',
    'Pempelfort','Platz des Deutschen Handwerks','Schadowstraße',
    'Steinberg','Universität Ost','Vennhauser Allee','Völklinger Straße',
    'Wahler Straße','Weberstraße','Wehrhahn','Worringer Platz',
  ].sort(),
  'Лондон': [
    'Acton Town','Aldgate','Aldgate East','Alperton','Amersham',
    'Angel','Archway','Arnos Grove','Arsenal','Baker Street',
    'Balham','Bank','Barbican','Barking','Barkingside',
    'Barons Court','Battersea Power Station','Bayswater','Becontree',
    'Belsize Park','Bermondsey','Bethnal Green','Blackfriars',
    'Blackhorse Road','Bond Street','Borough','Bounds Green','Bow Road',
    'Brent Cross','Brixton','Bromley-by-Bow','Buckhurst Hill',
    'Burnt Oak','Caledonian Road','Camden Town','Canada Water',
    'Canary Wharf','Canning Town','Cannon Street','Canons Park',
    'Chalfont & Latimer','Chalk Farm','Chancery Lane','Charing Cross',
    'Chesham','Chigwell','Chiswick Park','Chorleywood','Clapham Common',
    'Clapham North','Clapham South','Cockfosters','Colindale',
    'Colliers Wood','Covent Garden','Dagenham East','Dagenham Heathway',
    'Debden','Dollis Hill','Ealing Broadway','Ealing Common',
    "Earl's Court",'East Acton','East Finchley','East Ham','East Putney',
    'Eastcote','Edgware','Edgware Road','Elephant & Castle','Elm Park',
    'Embankment','Epping','Euston','Euston Square','Fairlop',
    'Farringdon','Finchley Central','Finchley Road','Finsbury Park',
    'Fulham Broadway','Gants Hill','Gloucester Road','Golders Green',
    'Goldhawk Road','Goodge Street','Grange Hill','Great Portland Street',
    'Greenford','Green Park','Gunnersbury','Hainault','Hammersmith',
    'Harlesden','Harrow & Wealdstone','Harrow-on-the-Hill','Hatton Cross',
    'Heathrow Terminal 2 & 3','Heathrow Terminal 4','Heathrow Terminal 5',
    'Hendon Central','High Barnet','Highbury & Islington','Highgate',
    'High Street Kensington','Hillingdon','Holborn','Holland Park',
    'Holloway Road','Hornchurch','Hounslow Central','Hounslow East',
    'Hounslow West','Ickenham','Kennington','Kensington (Olympia)',
    'Kentish Town','Kew Gardens','Kilburn','Kilburn Park',
    "King's Cross St. Pancras",'Kingsbury','Knightsbridge',
    'Lambeth North','Lancaster Gate','Latimer Road','Leicester Square',
    'Leyton','Leytonstone','Limehouse','Liverpool Street','Loughton',
    'Maida Vale','Manor House','Mansion House','Marble Arch',
    'Marylebone','Mile End','Mill Hill East','Monument','Moorgate',
    'Morden','Mornington Crescent','Neasden','North Acton',
    'North Ealing','North Greenwich','North Harrow','North Wembley',
    'Northfields','Northolt','Northwick Park','Northwood',
    'Northwood Hills','Notting Hill Gate','Oakwood','Old Street',
    'Osterley','Oval','Oxford Circus','Paddington','Park Royal',
    'Parsons Green','Perivale','Piccadilly Circus','Pimlico',
    'Pinner','Plaistow','Preston Road','Putney Bridge','Queensbury',
    'Queensway','Ravenscourt Park','Rayners Lane','Redbridge',
    'Richmond','Rickmansworth','Roding Valley','Royal Oak',
    'Ruislip','Ruislip Gardens','Ruislip Manor','Seven Sisters',
    'Shepherd\'s Bush','Sloane Square','Snaresbrook','South Ealing',
    'South Harrow','South Kensington','South Kenton','South Ruislip',
    'South Wimbledon','South Woodford','Southfields','Southgate',
    'Southwark','St. James\'s Park','St. John\'s Wood','St. Paul\'s',
    'Stamford Brook','Stanmore','Stepney Green','Stockwell',
    'Stonebridge Park','Stratford','Sudbury Hill','Sudbury Town',
    'Surrey Quays','Swiss Cottage','Temple','Theydon Bois',
    'Tooting Bec','Tooting Broadway','Tottenham Court Road',
    'Tottenham Hale','Tower Hill','Tufnell Park','Turnham Green',
    'Turnpike Lane','Upminster','Upminster Bridge','Upney','Upton Park',
    'Uxbridge','Vauxhall','Victoria','Walthamstow Central','Wanstead',
    'Warren Street','Warwick Avenue','Waterloo','Watford','Wembley Central',
    'Wembley Park','West Acton','West Brompton','West Finchley',
    'West Ham','West Hampstead','West Harrow','West Kensington',
    'West Ruislip','Westbourne Park','Westminster','White City',
    'Whitechapel','Willesden Green','Willesden Junction',
    'Wimbledon','Wimbledon Park','Wood Green','Wood Lane',
    'Woodford','Woodside Park',
  ].sort(),
  'Манчестер': [
    'Abraham Moss','Altrincham','Anchorage','Ashton-under-Lyne',
    'Besses o\' th\' Barn','Broadway','Bury','Castlefield',
    'Chorlton','Cornbrook','Crumpsall','Deansgate-Castlefield',
    'East Didsbury','Eccles','Exchange Quay','Exchange Square',
    'Failsworth','Firswood','Harbour City','Holt Town',
    'Ladywell','Langworthy','Manchester Airport','Market Street',
    'MediaCityUK','Milnrow','Monsall','Navigation Road',
    'New Islington','Newbury','Newhey','Newton Heath and Moston',
    'Oldham King Street','Oldham Mumps','Piccadilly','Piccadilly Gardens',
    'Pomona','Queens Road','Radcliffe','Rochdale Town Centre',
    'Salford Crescent','Salford Quays','Sale','Shaw and Crompton',
    'Shudehill','South Chadderton','St Peter\'s Square','Stretford',
    'The Trafford Centre','Timperley','TraffordCity','Victoria',
    'Whitefield','Woodlands Road','Wythenshawe Town Centre',
  ].sort(),
  'Ливерпуль': [
    'Aigburth','Aintree','Ainsdale','Bache','Bank Hall','Birkenhead Central',
    'Birkenhead North','Birkenhead Park','Blundellsands & Crosby',
    'Bootle New Strand','Bootle Oriel Road','Brunswick','Central',
    'Conway Park','Crosby & Blundellsands','Crossens','Fazakerley',
    'Formby','Freshfield','Garston','Hall Road','Hamilton Square',
    'Hillside','Hunts Cross','Hightown','James Street','Kirkby',
    'Kirkdale','Lime Street','Liverpool Central','Maghull','Mersey Rail',
    'Meols','Moorfields','Netherton','New Brighton','Neston',
    'Norris Green','Old Roan','Ormskirk','Orrell Park',
    'Rock Ferry','Sandhills','Seaforth & Litherland','Southport',
    'St Michaels','Thatto Heath','Town Green','Wallasey Grove Road',
    'Wallasey Village','Waterloo','West Allerton','West Kirby',
  ].sort(),
  'Глазго': [
    'Bridge Street','Buchanan Street','Cessnock','Cowcaddens',
    'Govan','Hillhead','Ibrox','Kelvinbridge','Kelvinhall',
    'Partick','St. Enoch','West Street',
  ],
  'Нью-Йорк': [
    '1st Avenue','2nd Avenue','3rd Avenue–138th Street','4th Avenue/9th Street',
    '5th Avenue/53rd Street','5th Avenue–59th Street','7th Avenue',
    '8th Avenue','8th Street–NYU','9th Avenue',
    '14th Street/6th Avenue','14th Street/8th Avenue','14th Street–Union Square',
    '15th Street–Prospect Park','18th Avenue','18th Street','20th Avenue',
    '21st Street','21st Street–Queensbridge','23rd Street','25th Avenue',
    '25th Street','28th Street','30th Avenue','33rd Street',
    '34th Street–Herald Square','34th Street–Hudson Yards','34th Street–Penn Station',
    '36th Avenue','36th Street','39th Avenue','42nd Street–Bryant Park',
    '42nd Street–Port Authority','45th Street','46th Street',
    '47th–50th Streets–Rockefeller Center','49th Street','50th Street',
    '52nd Street','53rd Street','55th Street','57th Street',
    '57th Street–7th Avenue','59th Street','59th Street–Columbus Circle',
    '61st Street–Woodside','63rd Drive–Rego Park','65th Street',
    '66th Street–Lincoln Center','67th Avenue','68th Street–Hunter College',
    '69th Street','71st Street','72nd Street','75th Avenue',
    '77th Street','79th Street','80th Street',
    '81st Street–Museum of Natural History','82nd Street–Jackson Heights',
    '86th Street','88th Street','90th Street–Elmhurst Avenue',
    '96th Street','103rd Street','103rd Street–Corona Plaza',
    '104th Street','111th Street','116th Street','116th Street–Columbia University',
    '121st Street','125th Street','135th Street','137th Street–City College',
    '145th Street','149th Street–Grand Concourse','155th Street',
    '161st Street–Yankee Stadium','163rd Street–Amsterdam Avenue',
    '167th Street','168th Street','169th Street','174th–175th Streets',
    '176th Street','181st Street','182nd–183rd Streets','190th Street',
    '191st Street','207th Street','215th Street','219th Street',
    '225th Street','231st Street','238th Street','242nd Street',
    'Aqueduct–North Conduit Avenue','Aqueduct Racetrack',
    'Atlantic Avenue–Barclays Center','Avenue H','Avenue I','Avenue J',
    'Avenue M','Avenue N','Avenue P','Avenue U','Avenue X',
    'Bay 50th Street','Bay Parkway','Bay Ridge–95th Street','Bay Ridge Avenue',
    'Beach 105th Street','Beach 25th Street','Beach 36th Street',
    'Beach 44th Street','Beach 60th Street','Beach 67th Street',
    'Beach 90th Street','Beach 98th Street',
    'Bedford Avenue','Bedford Park Boulevard','Bergen Street','Beverly Road',
    'Botanic Garden','Borough Hall','Bowery','Bowling Green',
    'Broad Channel','Broad Street','Broadway','Broadway Junction',
    'Broadway–Lafayette Street','Bronx Park East','Brook Avenue',
    'Brookhaven','Brooklyn Bridge–City Hall','Briarwood',
    'Burnside Avenue','Canarsie–Rockaway Parkway','Canal Street',
    'Castle Hill Avenue','Cathedral Parkway','Central Avenue','Chambers Street',
    'Church Avenue','City Hall','Clark Street','Classon Avenue',
    'Cleveland Street','Clinton–Washington Avenues','Coney Island–Stillwell Avenue',
    'Cortelyou Road','Court Square','Court Street','Crown Heights–Utica Avenue',
    'Crescent Street','Cypress Avenue','Cypress Hills','DeKalb Avenue',
    'Delancey Street–Essex Street','Ditmas Avenue','Dyckman Street',
    'East 105th Street','East 143rd Street–St Mary\'s Street',
    'East 149th Street','East 177th Street–Parkchester',
    'East 180th Street','Eastern Parkway–Brooklyn Museum',
    'Elder Avenue','Euclid Avenue','Far Rockaway–Mott Avenue',
    'Flatbush Avenue–Brooklyn College','Flushing–Main Street',
    'Fordham Road','Forest Hills–71st Avenue','Franklin Avenue',
    'Franklin Street','Fresh Pond Road','Fulton Street',
    'Gates Avenue','Grand Army Plaza','Grand Avenue–Newtown',
    'Grand Central–42nd Street','Grand Concourse','Grant Avenue',
    'Greenpoint Avenue','Gun Hill Road','Halsey Street','High Street',
    'Hoyt Street','Hoyt–Schermerhorn Streets','Hunt\'s Point Avenue',
    'Intervale Avenue','Jackson Avenue','Jamaica–179th Street',
    'Jamaica–Van Wyck','Jay Street–MetroTech','Jefferson Street',
    'Junction Boulevard','Junius Street','Kings Highway','Kingston Avenue',
    'Kingston–Throop Avenues','Kingsbridge Road','Knickerbocker Avenue',
    'Lexington Avenue–59th Street','Lexington Avenue–63rd Street',
    'Liberty Avenue','Livonia Avenue','Lorimer Street','Lefferts Boulevard',
    'Marcy Avenue','Merrick Boulevard','Metropolitan Avenue',
    'Mets–Willets Point','Middle Village–Metropolitan Avenue',
    'Middletown Road','Montrose Avenue','Morgan Avenue','Morris Avenue',
    'Myrtle Avenue','Myrtle–Willoughby Avenues','Nassau Avenue',
    'Neck Road','Neptune Avenue','New Lots Avenue','Newkirk Avenue',
    'Norwood–205th Street','Nostrand Avenue','Ozone Park–Lefferts Blvd',
    'Park Place','Park Street','Parkside Avenue','Parsons Blvd',
    'Pelham Bay Park','Pelham Parkway','Penn Station–34th Street',
    'President Street–Medgar Evers College','Prince Street',
    'Queens Plaza','Queensboro Plaza','Queensbridge',
    'Ralph Avenue','Rector Street','Rockaway Avenue','Rockaway Boulevard',
    'Rockaway Park–Beach 116th Street','Roosevelt Island',
    'Saratoga Avenue','Seneca Avenue','Shepherd Avenue',
    'Simpson Street','Smith–9th Streets','Speakman Place',
    'Spring Street','Sutter Avenue','Sutphin Blvd–Archer Ave–JFK Airport',
    'Times Square–42nd Street','Times Square–7th Avenue',
    'Tremont Avenue','Union Street','Utica Avenue',
    'Van Cortlandt Park–242nd Street','Van Siclen Avenue',
    'Wakefield–241st Street','Wall Street','West 4th Street',
    'West 8th Street–NY Aquarium','Whitehall Street–South Ferry',
    'Whitlock Avenue','Wilson Avenue','Wood Avenue','Woodhaven Boulevard',
    'Woodlawn','World Trade Center','York Street',
  ].sort(),
  'Лос-Анджелес': [
    '1st Street','5th Street','7th Street/Metro Center','17th Street/SMC',
    '26th Street/Bergamot','103rd Street/Watts Towers','Allen',
    'Anaheim Street','APU/Citrus College','Arcadia','Artesia','Atlantic',
    'Avalon','Aviation/Century','Aviation/Imperial','Azusa Downtown',
    'Chinatown','Civic Center/Grand Park','Compton','Crenshaw',
    'Culver City','Del Amo','Del Mar','Douglas','Downtown Inglewood',
    'Downtown Long Beach','Downtown Santa Monica','Duarte/City of Hope',
    'East LA Civic Center','El Segundo','Expo/Bundy','Expo/Crenshaw',
    'Expo/La Brea','Expo/Sepulveda','Expo/Vermont','Expo/Western',
    'Expo Park/USC','Fairview Heights','Farmdale','Fillmore','Firestone',
    'Florence','Glendora','Grand Avenue Arts/Bunker Hill','Grand/LATTC',
    'Harbor Freeway','Hawthorne/Lennox','Heritage Square','Highland Park',
    'Historic Broadway','Hollywood/Highland','Hollywood/Vine','Hollywood/Western',
    'Hyde Park','Indiana','Irwindale','Jefferson/USC','La Cienega/Jefferson',
    'LAX/Metro Transit Center','Lake','Lakewood Boulevard',
    'LATTC/Ortho Institute','La Verne/Fairplex','Leimert Park',
    'Little Tokyo/Arts District','Lincoln/Cypress','Lynwood','Maravilla',
    'Mariachi Plaza','Mariposa','Martin Luther King Jr.','Memorial Park',
    'Monrovia','North Hollywood','Norwalk','Pacific Avenue',
    'Pacific Coast Highway','Palms','Pershing Square','Pico','Pico/Aliso',
    'Pomona North','Redondo Beach','San Dimas','San Pedro Street',
    'Sierra Madre Villa','Slauson','Soto','South Pasadena',
    'Southwest Museum','Union Station','Universal City/Studio City',
    'Vermont/Athens','Vermont/Beverly','Vermont/Santa Monica',
    'Vermont/Sunset','Vernon','Wardlow','Washington',
    'Westchester/Veterans','Westlake/MacArthur Park','Westwood/Rancho Park',
    'Willow Street','Willowbrook/Rosa Parks','Wilshire/Normandie',
    'Wilshire/Vermont','Wilshire/Western',
  ].sort(),
  'Чикаго': [
    '18th','35th–Bronzeville–IIT','35th/Archer','43rd','47th','51st',
    '54th/Cermak','63rd','69th','79th','87th','95th/Dan Ryan',
    'Adams/Wabash','Addison (Blue Line)','Addison (Brown Line)','Addison (Red Line)',
    'Argyle','Armitage','Ashland (Green/Pink)','Ashland (Orange)',
    'Austin (Blue Line)','Austin (Green Line)','Belmont (Blue Line)',
    'Belmont (Brown/Purple/Red)','Berwyn','Bryn Mawr',
    'California (Blue Line)','California (Green Line)','California (Pink Line)',
    'Central (Green Line)','Central (Purple Line)','Central Park',
    'Cermak–Chinatown','Chicago (Blue Line)','Chicago (Brown/Purple)',
    'Chicago (Red Line)','Cicero (Blue Line)','Cicero (Green Line)',
    'Cicero (Pink Line)','Clark/Division','Clark/Lake','Clinton (Blue Line)',
    'Clinton (Green/Pink)','Conservatory–Central Park Drive',
    'Cottage Grove','Cumberland','Damen (Blue Line)','Damen (Brown Line)',
    'Damen (Green Line)','Damen (Pink Line)','Davis','Dempster',
    'Dempster–Skokie','Diversey','Division','Forest Park','Foster',
    'Francisco','Fullerton','Garfield (Green Line)','Garfield (Red Line)',
    'Grand (Blue Line)','Grand (Red Line)','Granville','Halsted (Green)',
    'Halsted (Orange)','Harlem (Blue Line Forest Park)',
    'Harlem (Blue Line O\'Hare)','Harlem/Lake',
    'Harold Washington Library–State/Van Buren','Harrison',
    'Howard','Illinois Medical District','Indiana','Irving Park (Blue)',
    'Irving Park (Brown)','Jackson (Blue Line)','Jackson (Red Line)',
    'Jarvis','Jefferson Park','Kedzie (Brown Line)','Kedzie (Green Line)',
    'Kedzie (Orange Line)','Kedzie (Pink Line)','Kedzie–Homan',
    'Kimball','King Drive','Kostner','Lake','Laramie','LaSalle',
    'LaSalle/Van Buren','Lawrence','Linden','Logan Square','Loyola',
    'Main','Merchandise Mart','Midway','Monroe (Blue)','Monroe (Red)',
    'Montrose (Blue Line)','Montrose (Brown Line)','Morgan','Morse',
    'North/Clybourn','Noyes','O\'Hare','Oak Park (Blue)','Oak Park (Green)',
    'Oakton–Skokie','Paulina','Polk','Pulaski (Blue)','Pulaski (Green)',
    'Pulaski (Orange)','Pulaski (Pink)','Quincy','Racine','Ridgeland',
    'Rockwell','Roosevelt','Rosemont','Sedgwick','Sheridan',
    'South Boulevard','Southport','Sox–35th','State/Lake','Thorndale',
    'UIC–Halsted','Washington (Blue)','Washington/Wabash','Washington/Wells',
    'Wellington','Western (Blue O\'Hare)','Western (Blue Forest Park)',
    'Western (Brown)','Western (Orange)','Western (Pink)','Wilson',
  ].sort(),
  'Вашингтон': [
    'Addison Road','Anacostia','Archives','Arlington Cemetery','Ashburn',
    'Ballston–MU','Benning Road','Bethesda','Braddock Road','Branch Avenue',
    'Brookland–CUA','Capitol Heights','Capitol South','Cheverly','Clarendon',
    'Cleveland Park','College Park–University of Maryland','Columbia Heights',
    'Congress Heights','Court House','Crystal City','Deanwood',
    'Downtown Largo','Dulles International Airport','Dunn Loring',
    'Dupont Circle','East Falls Church','Eastern Market','Eisenhower Avenue',
    'Farragut North','Farragut West','Federal Center SW','Federal Triangle',
    'Foggy Bottom–GWU','Forest Glen','Fort Totten','Franconia–Springfield',
    'Friendship Heights','Gallery Place','Georgia Avenue–Petworth','Glenmont',
    'Greenbelt','Greensboro','Grosvenor–Strathmore','Herndon','Huntington',
    'Hyattsville Crossing','Innovation Center','Judiciary Square',
    'King Street–Old Town','L\'Enfant Plaza','Landover','Loudoun Gateway',
    'McLean','McPherson Square','Medical Center','Metro Center',
    'Minnesota Avenue','Morgan Boulevard','Mount Vernon Square',
    'Navy Yard–Ballpark','Naylor Road','New Carrollton',
    'NoMa–Gallaudet U','North Bethesda','Pentagon','Pentagon City',
    'Potomac Avenue','Potomac Yard','Reston Town Center',
    'Rhode Island Avenue','Rockville','Reagan National Airport',
    'Rosslyn','Shady Grove','Shaw–Howard University','Silver Spring',
    'Smithsonian','Southern Avenue','Spring Hill','Stadium–Armory',
    'Suitland','Takoma','Tenleytown–AU','Twinbrook','Tysons',
    'U Street','Union Station','Van Dorn Street','Van Ness–UDC',
    'Vienna','Virginia Square–GMU','Waterfront','West Falls Church',
    'West Hyattsville','Wheaton','Wiehle–Reston East','Woodley Park',
  ].sort(),
  'Сан-Франциско': [
    '12th Street Oakland','16th Street Mission','19th Street Oakland',
    '24th Street Mission','Antioch','Ashby','Balboa Park','Bay Fair',
    'Castro Valley','Civic Center/UN Plaza','Coliseum','Concord',
    'Daly City','Downtown Berkeley','Dublin/Pleasanton','El Cerrito del Norte',
    'El Cerrito Plaza','Embarcadero','Fremont','Fruitvale','Glen Park',
    'Hayward','Lake Merritt','MacArthur','Millbrae','Milpitas',
    'Montgomery Street','North Berkeley','North Concord/Martinez',
    'Oakland International Airport','Orinda','Pittsburg/Bay Point',
    'Pittsburg Center','Pleasant Hill','Powell Street','Richmond',
    'Rockridge','San Bruno','San Francisco International Airport',
    'San Leandro','Santa Clara','South Fremont/Warm Springs',
    'South Hayward','South San Francisco','Union City','Walnut Creek',
    'West Dublin/Pleasanton','West Oakland',
  ].sort(),
  'Майами': [
    'Allapattah','Airport','Brickell','Brownsville','Civic Center',
    'Coconut Grove','Culmer','Dadeland North','Dadeland South',
    'Douglas Road','Dr. Martin Luther King Jr. Plaza','Earlington Heights',
    'Government Center','Hialeah','Northside','Okeechobee',
    'Overtown/Arena','Palmetto','Santa Clara','South Miami',
    'Tri-Rail/Metrorail Transfer','Vizcaya',
  ].sort(),
  'Сеул': [
    'Anguk','Apgujeong','Banpo','City Hall','Dongdaemun',
    'Dongdaemun History & Culture Park','Dongjak','Express Bus Terminal',
    'Euljiro 1-ga','Euljiro 3-ga','Euljiro 4-ga','Gangnam','Gangnam-gu Office',
    'Garosu-gil','Gimpo International Airport','Gubanpo','Guui',
    'Gyeongbokgung','Hapjeong','Hongik University',
    'Incheon International Airport Terminal 1',
    'Incheon International Airport Terminal 2',
    'Itaewon','Jamsil','Jamsil Stadium','Jongno 3-ga','Jonggak',
    'Konkuk University','Korail','Kyunghee University','Mapo',
    'Mapo-gu Office','Mok-dong','Myeongdong','Noryangjin',
    'Olympic Park','Samgakji','Samsung','Sangbong','Seoul Station',
    'Seolleung','Sindorim','Sinchon','Sinsa','Sookmyung Women\'s University',
    'Sports Complex','Sungshin Women\'s University','Sunae',
    'Suseo','Uijeongbu','Wangshipni','Yangjae','Yeouido','Yonsei University',
  ].sort(),
  'Пусан': [
    'Beomil','Busan Station','Centum City','Deokcheon','Dongnae',
    'Dusil','Gaegeum','Gwangalli','Haeundae','Hugok',
    'Jungang','Lotte World','Minam','Namcheon','Nampodong',
    'Noryangjin','Oncheonjang','Sajik','Sasang','Seomyeon',
    'Shin Gyeongju','Suyeong','Taejong Park','Yangsan',
  ].sort(),
  'Инчхон': [
    'Bupyeong','Dongam','Ganseok','Incheon City Hall',
    'International Business District','Juan','Woninjae',
    'Bupyeong-gu Office','Gyeyang','Geomdan Oryu','Incheon Grand Park',
  ].sort(),
  'Тэгу': [
    'Banwoldang','Chilgok Gyeongsangbuk-do Office','Daegu Station',
    'Dongdaegu Station','Duryu','Myeongdeok','Sincheon',
    'Angeup','Bisan','Daemyeong','Wolbae',
  ].sort(),
  'Тэджон': [
    'Daejeon Station','Government Complex Daejeon',
    'Jungangno','Tongil','Yongmun','Banseok','Jeonnong',
    'Pangyo','Sinheung','Wolpyeong',
  ].sort(),
  'Кванджу': [
    'Culture Complex','Gwangju Station','Nongseong','Sonjeong',
    'Dorim','Geumnamno 4-ga','Gyerim','Hanam','Sangmu',
    'Sinchang','Unnam',
  ].sort(),
}
